[project]
name = "pyreportsgen"
version = "0.1.0"
authors = [
    {name = "Ciro Fabian Bermudez Marquez"}
]
requires-python = ">= 3.9"
dependencies = [
    "numpy >= 2.3.4",
    "pandas >= 2.3.3",
    "matplotlib >= 3.10.7"
]
   